In [1]:
pip install numpy==1.26.4

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
print(a)

[1 2 3 4 5]


In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.array([1,2.45,3,4,5])

In [9]:
print(b)

[1.   2.45 3.   4.   5.  ]


In [10]:
b.dtype

dtype('float64')

In [11]:
a.shape

(5,)

In [12]:
b.shape

(5,)

In [13]:
a.size

5

In [14]:
a.min()

1

In [15]:
a.max()

5

In [16]:
b[3]

4.0

In [17]:
b[3]=6

In [18]:
b

array([1.  , 2.45, 3.  , 6.  , 5.  ])

In [19]:
b[-1]

5.0

In [20]:
b[-5]

1.0

In [21]:
b[1:3]

array([2.45, 3.  ])

In [22]:
arr = np.array([[1,2,3], [4,5,6]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr.shape

(2, 3)

In [25]:
arr[0][1]=7

In [26]:
arr

array([[1, 7, 3],
       [4, 5, 6]])

In [27]:
new=np.transpose(arr)

In [28]:
new

array([[1, 4],
       [7, 5],
       [3, 6]])

In [29]:
new.ravel()

array([1, 4, 7, 5, 3, 6])

In [30]:
arr.ravel()

array([1, 7, 3, 4, 5, 6])

In [31]:
arr.reshape(3,2)

array([[1, 7],
       [3, 4],
       [5, 6]])

In [32]:
arr.reshape(2,3)

array([[1, 7, 3],
       [4, 5, 6]])

In [33]:
arr.reshape(6,1)

array([[1],
       [7],
       [3],
       [4],
       [5],
       [6]])

In [34]:
arr.reshape(1,6)

array([[1, 7, 3, 4, 5, 6]])

In [35]:
threed=np.array([[1,2,3], [4,5,6],[7,8,9]])

In [36]:
threed

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
t=threed.transpose()

In [38]:
t

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [39]:
threed.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
t.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [41]:
t.reshape(9,1)

array([[1],
       [4],
       [7],
       [2],
       [5],
       [8],
       [3],
       [6],
       [9]])

In [42]:
threed=np.array([[1,2,3], [4,5,6],[7,8,9]])

In [43]:
threed.ndim

2

In [44]:
threed=np.array([[[1,2,3], [4,5,6],[7,8,9]]])

In [45]:
threed.ndim

3

In [46]:
threed

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [47]:
threed[0][1]=12

In [48]:
threed

array([[[ 1,  2,  3],
        [12, 12, 12],
        [ 7,  8,  9]]])

In [49]:
threed[0][2]=12

In [50]:
threed

array([[[ 1,  2,  3],
        [12, 12, 12],
        [12, 12, 12]]])

In [51]:
A=np.zeros((2,2))

In [52]:
A

array([[0., 0.],
       [0., 0.]])

In [53]:
t

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
t[1][1]

5

In [55]:
t[1][1]=10

In [56]:
t

array([[ 1,  4,  7],
       [ 2, 10,  8],
       [ 3,  6,  9]])

In [57]:
t[0][1]=11

In [58]:
t

array([[ 1, 11,  7],
       [ 2, 10,  8],
       [ 3,  6,  9]])

In [59]:
t[0][2]=12

In [62]:
t

array([[ 1, 11, 12],
       [ 2, 10,  8],
       [ 3,  6,  9]])

In [61]:
t.ravel()

array([ 1, 11, 12,  2, 10,  8,  3,  6,  9])

In [63]:
np.append(t,3)

array([ 1, 11, 12,  2, 10,  8,  3,  6,  9,  3])

In [64]:
t=np.insert(t,1,2)

In [65]:
t

array([ 1,  2, 11, 12,  2, 10,  8,  3,  6,  9])

In [74]:
c=[1,2,3,4,5]

In [75]:
np.median(c)

3.0

In [76]:
np.mean(c)

3.0

In [81]:
np.mode(c)

AttributeError: module 'numpy' has no attribute 'mode'