In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import pandas as pd

In [4]:
pip install  matplotlib

Note: you may need to restart the kernel to use updated packages.


In [5]:
import matplotlib.pyplot as pt

In [6]:
%matplotlib inline

In [7]:
df=pd.read_csv("C:\\Users\\aedur\\Downloads\\Admission_Predict (2).csv")

In [8]:
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,Yes,0.92
1,2,324,107,4,4.0,4.5,8.87,Yes,0.76
2,3,316,104,3,3.0,3.5,8.00,Yes,0.72
3,4,322,110,3,3.5,2.5,8.67,Yes,0.80
4,5,314,103,2,2.0,3.0,8.21,No,0.65
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,Yes,0.82
396,397,325,107,3,3.0,3.5,9.11,Yes,0.84
397,398,330,116,4,5.0,4.5,9.45,Yes,0.91
398,399,312,103,3,3.5,4.0,8.78,No,0.67


In [9]:
df2=df.drop("Serial No.",axis=1)

In [10]:
df2

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,Yes,0.92
1,324,107,4,4.0,4.5,8.87,Yes,0.76
2,316,104,3,3.0,3.5,8.00,Yes,0.72
3,322,110,3,3.5,2.5,8.67,Yes,0.80
4,314,103,2,2.0,3.0,8.21,No,0.65
...,...,...,...,...,...,...,...,...
395,324,110,3,3.5,3.5,9.04,Yes,0.82
396,325,107,3,3.0,3.5,9.11,Yes,0.84
397,330,116,4,5.0,4.5,9.45,Yes,0.91
398,312,103,3,3.5,4.0,8.78,No,0.67


In [11]:
df2=df.drop(["Serial No.","GRE Score","TOEFL Score","University Rating","SOP","LOR ","Research"],axis=1)

In [12]:
df2

,CGPA,Chance of Admit
0,9.65,0.92
1,8.87,0.76
2,8.00,0.72
3,8.67,0.80
4,8.21,0.65
...,...,...
395,9.04,0.82
396,9.11,0.84
397,9.45,0.91
398,8.78,0.67


In [15]:
x=df2.iloc[:,0].values.reshape(-1,1)
y=df2.iloc[:,1].values.reshape(-1,1)

In [16]:
x

array([[9.65],
       [8.87],
       [8.  ],
       [8.67],
       [8.21],
       [9.34],
       [8.2 ],
       [7.9 ],
       [8.  ],
       [8.6 ],
       [8.4 ],
       [9.  ],
       [9.1 ],
       [8.  ],
       [8.2 ],
       [8.3 ],
       [8.7 ],
       [8.  ],
       [8.8 ],
       [8.5 ],
       [7.9 ],
       [8.4 ],
       [9.5 ],
       [9.7 ],
       [9.8 ],
       [9.6 ],
       [8.8 ],
       [7.5 ],
       [7.2 ],
       [7.3 ],
       [8.1 ],
       [8.3 ],
       [9.4 ],
       [9.6 ],
       [9.8 ],
       [9.2 ],
       [8.4 ],
       [7.8 ],
       [7.5 ],
       [7.7 ],
       [8.  ],
       [8.2 ],
       [8.5 ],
       [9.1 ],
       [9.4 ],
       [9.1 ],
       [9.3 ],
       [9.7 ],
       [8.85],
       [8.4 ],
       [8.3 ],
       [7.9 ],
       [8.  ],
       [8.1 ],
       [8.  ],
       [7.7 ],
       [7.4 ],
       [7.6 ],
       [6.8 ],
       [8.3 ],
       [8.1 ],
       [8.2 ],
       [8.2 ],
       [8.5 ],
       [8.7 ],
       [8.92],
       [9.

In [17]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

## Splitting the data

In [18]:
pip install scikit-learn

  Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB 1.9 MB/s eta 0:00:06
   - -------------------------------------- 0.3/11.0 MB 5.4 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/11.0 MB 6.8 MB/s eta 0:00:02
   ---- ----------------------------------- 1.2/11.0 MB 7.5 MB/s eta 0:00:02
   ------ --------------------------------- 1.7/11.0 MB 8.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.3/11.0 MB 9.2 MB/s eta 0:00:01
   ---------- ----------------------------- 3.0/11.0 MB 10.2 MB/s eta 0:00:01
   ------------- -------------------------- 3.7/11.0 MB 10.7 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.0 MB 11.2 MB/s eta 0:00:01
   ------------------ -----------

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
y_test

array([[0.71],
       [0.7 ],
       [0.79],
       [0.73],
       [0.72],
       [0.48],
       [0.77],
       [0.71],
       [0.9 ],
       [0.94],
       [0.58],
       [0.89],
       [0.72],
       [0.57],
       [0.78],
       [0.42],
       [0.64],
       [0.84],
       [0.63],
       [0.72],
       [0.9 ],
       [0.83],
       [0.57],
       [0.47],
       [0.85],
       [0.67],
       [0.44],
       [0.54],
       [0.92],
       [0.62],
       [0.68],
       [0.73],
       [0.73],
       [0.61],
       [0.55],
       [0.74],
       [0.64],
       [0.89],
       [0.73],
       [0.95],
       [0.71],
       [0.72],
       [0.75],
       [0.76],
       [0.86],
       [0.7 ],
       [0.39],
       [0.79],
       [0.61],
       [0.64],
       [0.71],
       [0.8 ],
       [0.61],
       [0.89],
       [0.68],
       [0.79],
       [0.78],
       [0.52],
       [0.76],
       [0.88],
       [0.74],
       [0.49],
       [0.65],
       [0.59],
       [0.87],
       [0.89],
       [0.

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
lm=LinearRegression()

In [24]:
lm.fit(x_train,y_train)

LinearRegression()

In [25]:
ypredict=lm.predict(x_test)

In [26]:
ypredict

array([[0.71526369],
       [0.72367342],
       [0.75731236],
       [0.65219067],
       [0.75100506],
       [0.61855173],
       [0.74259533],
       [0.61644929],
       [0.8834584 ],
       [0.896073  ],
       [0.55547871],
       [0.86663893],
       [0.71526369],
       [0.43984484],
       [0.82879512],
       [0.6606004 ],
       [0.6353712 ],
       [0.83930729],
       [0.57440061],
       [0.74259533],
       [0.84140972],
       [0.83720485],
       [0.69634178],
       [0.45876675],
       [0.78043914],
       [0.60593712],
       [0.50081543],
       [0.6606004 ],
       [0.84771702],
       [0.65008823],
       [0.60593712],
       [0.71316125],
       [0.73418559],
       [0.60383469],
       [0.79095131],
       [0.74890263],
       [0.58070792],
       [0.85612676],
       [0.6542931 ],
       [0.94653142],
       [0.69423935],
       [0.6542931 ],
       [0.63957607],
       [0.78043914],
       [0.83089755],
       [0.59752739],
       [0.5239422 ],
       [0.675

In [27]:
comparison=pd.DataFrame(x_test,columns=["input Data"])

In [29]:
comparison["AVL O/P"]=y_test

In [30]:
comparison

,input Data,AVL O/P
0,8.56,0.71
1,8.60,0.70
2,8.76,0.79
3,8.26,0.73
4,8.73,0.72
...,...,...
75,8.20,0.61
76,8.36,0.69
77,8.43,0.62
78,9.54,0.93


In [31]:
comparison["Pred_O/P"]=ypredict

In [32]:
comparison

,input Data,AVL O/P,Pred_O/P
0,8.56,0.71,0.715264
1,8.60,0.70,0.723673
2,8.76,0.79,0.757312
3,8.26,0.73,0.652191
4,8.73,0.72,0.751005
...,...,...,...
75,8.20,0.61,0.639576
76,8.36,0.69,0.673215
77,8.43,0.62,0.687932
78,9.54,0.93,0.921302
